##
##  Makefile -- Build procedure for sample servertime Apache module
##  Autogenerated via ``apxs -n servertime -g''.
##

builddir=.
top_srcdir=/home/marko/micex/Projects/doupre/httpd
top_builddir=/home/marko/micex/Projects/doupre/httpd
include /home/marko/micex/Projects/doupre/httpd/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_servertime.o mod_servertime.lo mod_servertime.slo mod_servertime.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/servertime

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

